### ISSUE TITLE
Test against different versions of shelljs

### ISSUE THREAD

**Issue by nfischer** [shelljs/benchmarks#2]
Requiring multiple versions of the same package is somewhat frowned upon in the node community, but here's a suggested workaround from isaacs:

https://github.com/npm/npm/issues/5499#issuecomment-71089080

We might consider investigating this in order to test against versions 0.5.3 and up. Or we can switch to requiring the latest version of shelljs and testing against that.

It might be worth it to investigate some sort of API for generating online graphs, so we can check performance changes over time, on average.

**Comment by freitagbr** [comment]
[Here's](https://nodejs.org/en/blog/uncategorized/profiling-node-js/) an article on profiling Node.js applications using `dtrace` and `stackvis`.

Also, Brendan Gregg's [FlameGraph](https://github.com/brendangregg/FlameGraph) tool.

**Comment by nfischer** [comment]
Testing against different versions has been resolved. Let's get it running as-is and then experiment with graphs.
