### ISSUE TITLE
Please add information about your machine, node version, etc.

### ISSUE THREAD

**Issue by nfischer** [shelljs/benchmarks#3]
These stats aren't very helpful unless we have information about your machine's specs.

**Comment by nfischer** [comment]
Actually, it'd be even better if there was a way to log the specs from the last Travis run (if we set up Travis), in a pretty format like a markdown file. @ariporad Do you have any ideas for this?

**Comment by ariporad** [comment]
Hmm...

I'd have to think of a Creative Solution™*. Let me on this for a bit, I'll let you know.

<sub> \* Otherwise known as a horrible hack. </sub>

**Comment by ariporad** [comment]
Ok, So I had a really great idea:

> Generally, If a new commit triggers travis, then travis creates a new commit, that creates an infinite loop. This is bad. Additionally, we want a change of either shelljs OR the benchmarks to result in a re-bench.
> 
> So what we'll do is:
> 1. Move benchmark results to github pages, and make sure travis doesn't build the `gh-pages` branch. Alternatively, we could move them to a different repo.
> 2. In the travis for the benchmarks, run them against as many versions as we can, then upload the results to github pages.
> 3. Use [this](https://github.com/ajdm/travis-build-children) to re-run the benchmarks whenever shelljs builds.

Then I was helpfully reminded by travis-ci/travis-ci#352 that we can't be assured the specs of the machine that travis runs on, so that won't work.

So I don't really think that's possible. Unless we have another Creative Idea.

**Comment by nfischer** [comment]
I actually like this idea, and I think it could work well. It's true, from one run to another, we may see inconsistencies. However, for a given run, the only variable will be choice of "shell" (bash, shelljs v0.5, shelljsv0.6, etc.). We'll never see a given run of travis run the first half of the benchmark (bash) on different specs than the second half (shelljs), so the comparison is still valid.

All we have to do is add in logging functionality, so we actually see stats about the given machine, which gives people a frame of reference (and I believe #6 should help with that).

**Comment by ariporad** [comment]
@nfischer: Ok, in that case, here's what I think we should do:
1. Refactor this project into the following format:
    - A `tests/` dir, with one subdir for each test (ex. `tests/echoIntoFile`)
    - Each of those subdirs would then contain two files, `shelljs.js` and `bash.sh`. `shelljs.js` takes an `/absolute/path/to/shelljs` as an argument, bash doesn't.
    - It's then easy to run each test against many instances of shelljs, and against bash too.
2. Move benchmark results to gh-pages, and make sure travis doesn't build the `gh-pages` branch.
3. Travis for this repo ("the bench") runs the benchmarks and uploads to gh-pages.
5. ShellJS travis re-runs the latest build of this travis.

I'll try to implement this tomorrow morning, and I'll ping this thread when I've got something working.

**Comment by ariporad** [comment]
Also, does anyone mind if I rename this shelljs/benchmarks?

**Comment by nfischer** [comment]
+1 for renaming the project
1. That should be ok. If there's a way to requiring the path as an argument, that might be even better (we can use the transpiler to make writing scripts a bit easier). But the path as argument would be a very clean solution as well.
2. Sounds like a good solution
3. SGTM
4. I think that should only be done if we're pulling one of our shelljs versions from master's latest commit. Git submodules come to mind, but these typically lock onto a specific commit. Not sure if we can say "latest"

Also, I think we should have a `versions.txt` in each directory. Commands like `touch()` aren't supported for v0.5, so this file could specify `v0.6+`

**Comment by ariporad** [comment]
@nfischer: RE  #1: not really sure what you mean, but I think it's probably going to be easier to avoid transpiling if at all possible, but it might be a fairer solution.

As for #4, what we'll do is have the shelljs travis build trigger a rebuild of the benchmark travis. If we wanted to get fancy, the benchmark travis could be programmed to check for any shelljs commits it hadn't tested, and test as many as needed.

Another thing. I think we should test npm commits, and ignore tags and npm releases entirety. That Ok?

**Comment by ariporad** [comment]
Also, I think we should measure scores primarily as a bash vs shelljs ratio, not absolute times. Also, I think each run should test multiple times. Does 15 sound good?

**Comment by nfischer** [comment]
> If we wanted to get fancy, the benchmark travis could be programmed to check for any shelljs commits it hadn't tested, and test as many as needed.

I only see a benefit if we also have it pull down the latest version of shelljs and run that as an additional test.

> RE #1: not really sure what you mean

Actually, forget what I said. I think your proposal is the best way to go. It's a lot easier to just do `require(process.argv[2])`

> Also, I think we should measure scores primarily as a bash vs shelljs ratio, not absolute times. Also, I think each run should test multiple times. Does 15 sound good?

I agree that the ratio is more important (thanks @IvantheDugtrio for adding that feature). Maybe we could add a link to the times as well? If we implement github pages as an `index.html` (as opposed to `index.md`), we could consider letting the ratio be what we show on the page, and letting the time in seconds be shown as a tooltip.

Also, opting for html output means we can probably build up results in a more sane way than just appending text to the end of a markdown file.

**Comment by ariporad** [comment]
@nfischer: Ok, I think it makes the most sense to run the benchmarks once per shelljs master commit ($commit), and run the benchmarks against bash, $commit, the latest released version of shelljs, and maybe $commit's parent. Sound good?

**Comment by nfischer** [comment]
I like running against each version of shelljs, v0.5.3+. It tracks our progress over time. This brings with it the issue of checking for version (since commands like `touch()` are new), but I think it's worth it.

The rest sounds good to me.

**Comment by ariporad** [comment]
So you're thinking that each run would be like (bash, shelljs@0.5.3,
shelljs@0.6.0, shelljs@0.7.0, last commit, current commit)?

**Comment by nfischer** [comment]
Exactly. And I think it's ok if we hardcode the list, since it's easy enough to update

**Comment by nfischer** [comment]
I'm marking this as closed. This now runs on v0.5.3, v0.6, and the latest version of master. I'm hesitant to run on the previous commit on master, because sometimes commits can be in a broken state (unless we _insist_ that everyone squashes commits, which probably isn't the best way to get collaborators).

This deploys to `index.md` on the github pages branch and makes the commit. This should be changed to `index.html` I think, since I can't see anything on github pages yet.
