### ISSUE TITLE
Move to @shelljs.

### ISSUE THREAD

**Issue by ariporad** [shelljs/benchmarks#4]
Hi @IvantheDugtrio!

I was wondering if you'd consider allowing us to move this project in to the shelljs org? I've been trying to put more of an emphasis on performance in shelljs, and this tool looks really useful.

We would of course love for you to continue working on the project, and you would have full control of it. 

Thank you for your consideration

cc @nfischer.

**Comment by IvantheDugtrio** [comment]
Hi @ariporad 

I'd be happy to move the project to shelljs org. I'll get around that sometime this weekend.

**Comment by ariporad** [comment]
@IvantheDugtrio: Thanks so much!

I invited you to the shelljs org, and I _**think**_ that should be ok for transferring it, if not, let me know.

**Comment by nfischer** [comment]
@ariporad I had @IvantheDugtrio transfer it to me, so I should be able to then transfer it to the org right now.

**Comment by ariporad** [comment]
@nfischer: Fantastic! Can you give @shelljs/bench admin perms?

**Comment by nfischer** [comment]
Done :+1:

**Comment by ariporad** [comment]
Fantastic! Thanks!
