### ISSUE TITLE
Switch to index.html

### ISSUE THREAD

**Issue by nfischer** [shelljs/benchmarks#7]
Once we start building an `index.html` from benchmark run, Github pages should start displaying results. This should have a similar layout to the current `index.md` file.

**Comment by ariporad** [comment]
I have an idea, how about this:
- Travis only runs on master
- If something __other__ than the `results/` directory was changed, then re-run the benchmarks.
  - Upload the results to `results/MM-DD-YYYY-HH-MM-SS.json`, on `master`.
- If __only__ the `results/` directory was changed, regenerate the `gh-pages` branch.

**Comment by nfischer** [comment]
I don't quite follow. What is the results directory?

Right now it runs whenever Travis runs. So pushing to master is enough to rebuild gh-pages.

To actually make gh-pages visible, we need to have a file named index.html

**Comment by ariporad** [comment]
@nfischer: That would give us much more freedom with the results, as they would be stored on a directory on master. Then we can generate the website with a function `[Results] => String`.

**Comment by nfischer** [comment]
I was thinking we would load the results as they're created into a DOM-like object. Then we can write that object out into an `index.html` file. I don't see a use for saving things to the file system just to read them back off.

**Comment by nfischer** [comment]
The advantage to this is that we actually won't get diffs for each round of benchmarks. We can update our benchmark software without necessarily storing each set of results, but we can still have the latest results published to github pages

**Comment by ariporad** [comment]
However, if we say, wanted to generate a graph of the last 30 runs, or do anything else with the data after we've generated it, JSON files will be easier.

What I'm suggesting is basically a paradime shift, where we generate the data, then the website is simply one of the things we can generate from that data.

**Comment by nfischer** [comment]
What's the benefit of graphing the last 30 runs? Each run is on a different machine, so stats are incomparable. And that's 30 runs of v0.5.3, 30 runs of v0.6, and 30 runs of master. Of those 3, only master would ever change due to anything other than extraneous factors.

I think going off the last run, like we're currently doing, is better over all. This gives good comparisons of each version and of Bash, and it keeps data diffs out of the version control, which is another plus

**Comment by nfischer** [comment]
Ordinarily, I'd agree that more data points is better (even if we have 1 run of each released version, and 1 run of each of the last 10 or so commits). The main issue I see, however, is that we can't rely on travis environments being comparable. So we can't compare two different runs of travis.

**Comment by ariporad** [comment]
But we can compare shelljs time/bash time.

**Comment by nfischer** [comment]
I'd rather not compare bash/shelljs time across different systems, since there's too many variables. And this would of course invalidate the section that logs system specs, which is probably a step in the wrong direction.

And if we ever add in more tests, wouldn't we have to re-run everything?

**Comment by ariporad** [comment]
Hmm... Ok.

**Comment by ariporad** [comment]
@nfischer: [YAAAAAAAAAAAAAAAAY!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!](http://shelljs.github.io/benchmarks/)

**Comment by nfischer** [comment]
:+1:
